services:
  mongo:
    image: mongo:latest
    volumes:
      - ./mongo:/data/db
    hostname: mongo
    networks:
      - nicoarch

  redis:
    image: redis:latest
    hostname: redis
    networks:
      - nicoarch

  app:
    build:
      context: ./app
    volumes:
      - ${CONTENTS_DIR:-./contents}:/contents
    environment:
      - MONGO_URL=mongodb://mongo:27017/nicoarch
      - REDIS_URL=redis://redis:6379/0
    hostname: app
    depends_on:
      - mongo
      - redis
    networks:
      - nicoarch

  worker:
    build:
      context: ./worker
    volumes:
      - ${CONTENTS_DIR:-./contents}:/contents
      - ./worker/session:/app/session
    environment:
      - MONGO_URL=mongodb://mongo:27017/nicoarch
      - REDIS_URL=redis://redis:6379/0
      - NICONICO_MAIL=${NICONICO_MAIL}
      - NICONICO_PASSWORD=${NICONICO_PASSWORD}
    depends_on:
      - mongo
      - redis
    deploy:
      replicas: ${WORKER_COUNT:-1}
    networks:
      - nicoarch

  nginx:
    image: nginx:latest
    volumes:
      - ${CONTENTS_DIR:-./contents}:/contents
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_PORT:-8080}:80"
    depends_on:
      - app
      - worker
    networks:
      - nicoarch

networks:
  nicoarch:
    driver: bridge
